### ISSUE TITLE
For Python 2.7 ?

### ISSUE THREAD

**Issue by Jumitti** [besuper/TrackersRemover#2]
Yes I know, it's old, but on Mac you don't have Deluge in Python 3...

**Comment by besuper** [comment]
Hi, unfortunately I don't have access to this python version. I recommend you to build it from your Mac machine. You can clone the project and then run the command "python setup.py bdist_egg", it will generate the egg file that perfectly suit your environment.

**Comment by Jumitti** [comment]
Thanks for your quick reply @besuper! I made a [fork](https://github.com/Jumitti/TrackersRemover) of your repository.

Namely, your py3.7 version works on Mac (weird, other plug-ins don't work in 3.7) then I also modified a little thing. I don't know how to make a nice interface to, for example, change the time at which trackers are changed or to specify a particular tracker. So I just modified what I was interested in.
